### ISSUE TITLE
Effective React Development using Nx

### ISSUE THREAD

**Issue by rubiagatra** [reactjs-id/meetup#3]
## What is the title of your talk?

**Effective React Development using Nx**

## How long will your talk be?

45 - 60 Minutes.

## Brief description

Nx is a fast, smart, and extensible build system that helps teams develop
applications at any scale. It integrates with modern frameworks and libraries. It provides computation caching and smart rebuilds, as well as code generators. In this talk, we will explore how effectively scale React project using Nx.

### Introduction
If you’ve ever worked at a company with more than one team, chances are
you’ve had to deal with some challenges when it comes to change management.

In a typical work setting, development teams are divided by domain or technology. For example, one team building the UI in React, and another one building the API in Express. 

These teams usually have their own code repositories, so
changes to the software as a whole require juggling multiple repositories.

A few problems that arise from a multi-repository (often called “Polyrepo”)
setup include:
• Lack of collaboration because sharing code is hard and expensive.
• Lack of consistency in linting, testing, and release processes.
• Lack of developer mobility between projects because access may be unavailable or the development experience varies too greatly.
• Difficulty in coordinating changes across repositories.
• Late discovery of bugs because they can only occur at the point of integration rather than when code is changed.

### Monorepo to the rescue!
A lot of successful organizations such as Google, Facebook, and Microsoft–and
also large open-source projects such as Babel, Jest, and React–are all using the
monorepo approach to software development.

What is a monorepo though? A monorepo is a single repository containing
multiple distinct projects, where we don’t just have code collocation, but well-defined relationships among these projects. 

As you will see in this talk, the monorepo approach - when done correctly - can save developers a lot of headaches and wasted time.

Still, there are quite some misconceptions when it comes to monorepos.
• Monorepos are monolithic and not for building microservices and microfrontends1
• Continuous integration (CI) is slow
• “Everyone can change my code”
• Teams losing their autonomy

**Comment by r17x** [comment]
This issue was  **Done**. If you want to watch the video, see here https://www.youtube.com/watch?v=1pRNsg9jrzQ .
