### ISSUE TITLE
The Complete Guide to React Form Handling

### ISSUE THREAD

**Issue by mhaidarhanif** [reactjs-id/meetup#4]
## What is the title of your talk?

Demo: https://github.com/mhaidarhanif/demo-react-form

- "The Complete Guide to React Form Handling" 📖🙌
- "How to Handle Your Form Data in React" 📝👌
- "Kupas Tuntas Main Data Form di React" 🔪💪
  - "Dalam 1 SKS (Suka-Suka Saya)"
  - Voted by @zainfathoni 😂

Request to ask @r17x @resir014 @iamyuu to suggest more ideas. 🙏

## How long will your talk be?

- 60 minutes - Demo, live coding, and pair programming with @zainfathoni @r17x
- 90 minutes - Including QA (question/answer)
- 120 minutes - Including in-depth discussion
- 120+ minutes - Including the super party mode

## Brief description

English:

Let's end the insanity of form data handling in React. This is "The Complete Guide to React Form Handling". 😎

Indonesian:

Mari kita akhiri bencana mengatur data form di React. Ini adalah "Kupas Tuntas Main Data Form di React". 😎

Issue: https://github.com/reactjs-id/meetup/issues/4
Repo: https://github.com/mhaidarhanif/demo-react-form

## Detailed Overview

**Problems**

Handling form field data in React is sometimes confusing and the official docs are not really helping much. 🤷

- How to handle simple form fields?
- How to handle multiple complex form fields?
- How to submit the data through the network?
- How to implement the search form?
- How to submit and then navigate the pages?
- How to do autocomplete fields from the native browser and query params?
- How to implement the location/place search field?
- How to test if it works?
- How to do it better?
- How to do it faster?
- How to do it stronger?

**Solutions**

- Let it be like hell 😈
- First principles thinking
  - Identify and define your current assumptions
  - Breakdown the problem into its fundamental principles
  - Create new solutions from scratch
- Understand the native HTML form elements' behavior
  - `form`
  - `input`
  - `label`
  - `select`
  - `textarea`
  - `button`
  - `fieldset`
  - `legend`
  - `datalist`
  - `output`
  - `option`
  - `optgroup`
- Use TypeScript for safety
- Use an uncontrolled component approach with native form behavior 🧘
- Use a controlled component approach with a state 🏋️
- useState
- useReducer
- Patterns
  - Optimistic UI
- External library for submitting form data
  - React Hook Form (RHF)
    - Smart Form Component
  - Formik
  - React Router v6 to handle form
  - Tanstack React Form
  - Other alternatives
- External library for validating form data
  - Yup
  - Zod
  - Other resolvers
- External library for handling form fields with the UI
  - Downshift for autocomplete/Combobox or select dropdown components
  - Headless UI
  - Radix UI
  - Reach UI
- Specific cases
  - Client-side only
  - Framework-specific with server-side
    - Next.js
    - Remix
  - Network request
    - Subscribe to Newsletter
    - Authentication
  - Rich Text Editor
    - Tiptap
    - Lexical
    - Draft.js
  - Maps API
    - `use-places-autocomplete`
    - `react-mapbox-autocomplete` and `react-map-gl`
- Other suggestions are welcome

## References

- https://jamesclear.com/first-principles
- https://fs.blog/first-principles
- https://reactjs.org/docs/forms.html
- https://swyx.io/no-controlled-forms
- https://github.com/react-hook-form/resolvers
- https://remix.run/docs/en/v1/guides/data-writes
- https://github.com/react-hook-form/resolvers
- https://web.facebook.com/groups/442974152553174/posts/2172423456274893
- https://twitter.com/zainfathoni/status/1547901484196511746

## Discussions

- https://web.facebook.com/groups/442974152553174/posts/2177357949114777

**Comment by iamyuu** [comment]
Handling form di react router versi beta nggak masuk ya? Tapi harusnya sama kaya remix sih

**Comment by mhaidarhanif** [comment]
@iamyuu Bisa, barusan di-update ya. Baru inget ada itu, udah sempat cek juga.

@iamyuu Sure, just updated. Just remember about it, already checked it out.

**Comment by r17x** [comment]
So far so good @mhaidarhanif .

Next mungkin bikin group via Telegram yah buat bahas Meetup ini 

cc @iamyuu  @zainfathoni  @mhaidarhanif

**Comment by mhaidarhanif** [comment]
@r17x Awesome 👍 Sure, let's continue in the private chat group
