### ISSUE TITLE
State of CSS 2022

### ISSUE THREAD

**Issue by zainfathoni** [reactjs-id/meetup#6]
```[tasklist]
### Topics
- [x] https://2022.stateofcss.com/en-US/
- [x] Tailwind CSS drama
```

## Scheduled

Mari kita bikin ONAR lagi!
Kali ini insya Allah kita akan membahas hasil survei State of CSS 2022.

Sampai jumpa besok Sabtu, jam 10:00 WIB di YouTube ya! 😉

https://s.reactjs.id/obrolan-2

![ONAR #2 (1)](https://user-images.githubusercontent.com/6315466/227386222-45493288-ee8f-4a8d-a21c-389f66b970ed.png)

**Comment by mhaidarhanif** [comment]
Topics:

- Tailwind CSS ecosystem with unstyled/headless components
  - Headless UI, Radix UI, Ariakit, Downshift, etc
- The End of Front-End Development
  - https://www.joshwcomeau.com/blog/the-end-of-frontend-development

References:

- https://www.youtube.com/watch?v=gtb9OBhra5c (related to the Tailwind CSS drama)
- https://www.youtube.com/watch?v=CQuTF-bkOgc - CSS in 2023 - Tailwind vs MUI vs Bootstrap vs Chakra vs...

Images:

![image](https://user-images.githubusercontent.com/235584/227681729-840f4497-794c-4921-bb81-eb271d56a99d.png)

![image](https://user-images.githubusercontent.com/235584/227681782-8d1d26a0-bc9a-4dc7-bbeb-1320d4357348.png)

![Capture-2023-03-25-105613](https://user-images.githubusercontent.com/6315466/227686094-c54745c0-265e-4efd-8a95-d9843aa5e801.png)

**Comment by zainfathoni** [comment]
https://s.reactjs.id/obrolan-2
